from pynput import keyboard

classDD_mapping = {
    'Key.esc': 100,
    'Key.f1': 101,
    'Key.f2': 102,
    'Key.f3': 103,
    'Key.f4': 104,
    'Key.f5': 105,
    'Key.f6': 106,
    'Key.f7': 107,
    'Key.f8': 108,
    'Key.f9': 109,
    'Key.f10': 110,
    'Key.f11': 111,
    'Key.f12': 112,
    '`': 200,
    '1': 201,
    '2': 202,
    '3': 203,
    '4': 204,
    '5': 205,
    '6': 206,
    '7': 207,
    '8': 208,
    '9': 209,
    '0': 210,
    '-': 211,
    '=': 212,
    '\\': 213,
    'Key.backspace': 214,
    'Key.tab': 300,
    'q': 301,
    'w': 302,
    'e': 303,
    'r': 304,
    't': 305,
    'y': 306,
    'u': 307,
    'i': 308,
    'o': 309,
    'p': 310,
    '[': 311,
    ']': 312,
    'Key.caps_lock': 400,
    'a': 401,
    's': 402,
    'd': 403,
    'f': 404,
    'g': 405,
    'h': 406,
    'j': 407,
    'k': 408,
    'l': 409,
    ';': 410,
    "'": 411,
    'Key.shift': 500,
    'z': 501,
    'x': 502,
    'c': 503,
    'v': 504,
    'b': 505,
    'n': 506,
    'm': 507,
    ',': 508,
    '.': 509,
    "/": 510,
    "Key.shift_r":511,
    'Key.ctrl_l': 600,
    'Key.cmd': 601,
    'Key.alt_l': 602,
    'Key.space': 603,
    'hangul': 604,
    'Key.print_screen':700,
    'Key.scroll_lock': 701,
    'Key.pause': 702,
    'Key.insert': 703,
    'Key.home': 704,
    'Key.page_up': 705,
    'Key.delete': 706,
    'Key.end': 707,
    'Key.page_down': 708,
    'Key.up': 709,
    'Key.left': 710,
    'Key.down': 711,
    'Key.right': 712
}

key_mapping = {
    'Key.ctrl_l': 'ctrl',
    'Key.shift': 'shift',
    'Key.space': 'space',
    'Key.backspace': 'backspace',
    'Key.enter': 'enter',
    'Key.cmd': 'cmd',
    'Key.right': 'right',
    'Key.left': 'left',
    'Key.up': 'up',
    'Key.down': 'down',
    'Key.delete': 'delete',
    'Key.end': 'end',
    'Key.page_down': 'page_down',
    'Key.page_up': 'page_up',
    'Key.insert': 'insert',
    'Key.home': 'home'
}


ctrl_mapping = {
    keyboard.KeyCode.from_char('\x01'): keyboard.KeyCode.from_char('a'),
    keyboard.KeyCode.from_char('\x02'): keyboard.KeyCode.from_char('b'),
    keyboard.KeyCode.from_char('\x03'): keyboard.KeyCode.from_char('c'),
    keyboard.KeyCode.from_char('\x04'): keyboard.KeyCode.from_char('d'),
    keyboard.KeyCode.from_char('\x05'): keyboard.KeyCode.from_char('e'),
    keyboard.KeyCode.from_char('\x06'): keyboard.KeyCode.from_char('f'),
    keyboard.KeyCode.from_char('\x07'): keyboard.KeyCode.from_char('g'),
    keyboard.KeyCode.from_char('\x08'): keyboard.KeyCode.from_char('h'),
    keyboard.KeyCode.from_char('\x09'): keyboard.KeyCode.from_char('i'),
    keyboard.KeyCode.from_char('\x0A'): keyboard.KeyCode.from_char('j'),
    keyboard.KeyCode.from_char('\x0B'): keyboard.KeyCode.from_char('k'),
    keyboard.KeyCode.from_char('\x0C'): keyboard.KeyCode.from_char('l'),
    keyboard.KeyCode.from_char('\x0D'): keyboard.KeyCode.from_char('m'),
    keyboard.KeyCode.from_char('\x0E'): keyboard.KeyCode.from_char('n'),
    keyboard.KeyCode.from_char('\x0F'): keyboard.KeyCode.from_char('o'),
    keyboard.KeyCode.from_char('\x10'): keyboard.KeyCode.from_char('p'),
    keyboard.KeyCode.from_char('\x11'): keyboard.KeyCode.from_char('q'),
    keyboard.KeyCode.from_char('\x12'): keyboard.KeyCode.from_char('r'),
    keyboard.KeyCode.from_char('\x13'): keyboard.KeyCode.from_char('s'),
    keyboard.KeyCode.from_char('\x14'): keyboard.KeyCode.from_char('t'),
    keyboard.KeyCode.from_char('\x15'): keyboard.KeyCode.from_char('u'),
    keyboard.KeyCode.from_char('\x16'): keyboard.KeyCode.from_char('v'),
    keyboard.KeyCode.from_char('\x17'): keyboard.KeyCode.from_char('w'),
    keyboard.KeyCode.from_char('\x18'): keyboard.KeyCode.from_char('x'),
    keyboard.KeyCode.from_char('\x19'): keyboard.KeyCode.from_char('y'),
    keyboard.KeyCode.from_char('\x1A'): keyboard.KeyCode.from_char('z')
}